export type Role = 'gamer' | 'developer' | 'expert';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected';

export type User = {
  id: string;
  email: string;
  username: string;
  displayName: string;
  bio: string;
  avatarUri?: string;
  avatarId?: string;
  roles: Role[];
  skills: string[];
  games: string[];
  tags?: string[];
  portfolioUrl?: string;
  linkedinUrl?: string;
  location?: string;
  yearsExperience?: number;
  interests: string[];
  credibility: number;
  followers: number;
  following: number;
  posts: number;
  isExpert?: boolean;
  isAdmin: boolean;
  online?: boolean;
  avatarLook?: import('../data/gamerAvatars').AvatarLook;
  firstName: string;
  lastName: string;
  phone?: string;
  approvalStatus: ApprovalStatus;
  approvalRejectionReason?: string;
};
